TRANSPORT_CONGESTION_NORMAL = 50
TRANSPORT_CONGESTION_WARNING = 80
TRANSPORT_SPEED_CRITICAL = 25
TRANSPORT_INCIDENTS_HIGH = 3

ECOLOGY_AQI_NORMAL = 50
ECOLOGY_AQI_WARNING = 100

STATUS_NORMAL = "normal"
STATUS_WARNING = "warning"
STATUS_CRITICAL = "critical"

STATUS_COLORS = {
    STATUS_NORMAL: "#2ecc71",
    STATUS_WARNING: "#f39c12",
    STATUS_CRITICAL: "#e74c3c",
}

STATUS_LABELS = {
    STATUS_NORMAL: "Норма",
    STATUS_WARNING: "Внимание",
    STATUS_CRITICAL: "Критично",
}
